name: Metrics
on:
  schedule: [{ cron: "0 */6 * * *" }] # Atualiza a cada 6 horas
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: ViniciusKanh
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 6
